const test=require('node:test');const assert=require('node:assert/strict');const Module=require('node:module');
function load(options={}){const original=Module._load;const calls=[];const db={query:async(sql)=>{if(sql.includes('AI_FINE_TUNE_RUN'))return options.run===undefined?[{ID:12,ARTIFACT_ID:7,STATUS:'COMPLETED'}]:options.run;if(sql.includes('AI_FINE_TUNE_ARTIFACT'))return options.artifact===undefined?[{ID:7}]:options.artifact;if(sql.includes('AI_MODEL_VERSION'))return [];return [];},nextId:async()=>91,execute:async(sql,p)=>calls.push({sql,p}),dialect:()=>({limit:(sql,n)=>sql+' ROWS '+n})};Module._load=function(request,parent,isMain){if(request==='./db.service'&&parent?.filename?.endsWith('ai.model-version.service.js'))return db;return original.apply(this,arguments)};delete require.cache[require.resolve('../src/services/ai.model-version.service')];const service=require('../src/services/ai.model-version.service');Module._load=original;return{service,calls};}
const input=()=>({runId:12,artifactId:7,provider:'test',modelName:'candidate',modelVersion:'1',modelUri:'models/candidate',metadata:{eval:0.9}});
test('model hash is deterministic',()=>assert.equal(load().service.modelHash(input()),load().service.modelHash({...input()})));
test('validation requires provider and model',()=>assert.throws(()=>load().service.validate({}),e=>e.code==='AI_MODEL_PROVIDER_REQUIRED'));
test('model registration requires completed training run',async()=>{const {service}=load();const r=await service.create(7,input());assert.equal(r.id,91);assert.equal(r.status,'REGISTERED');});
test('model hash rejects malformed explicit hash',()=>assert.throws(()=>load().service.validate({...input(),modelHash:'bad'}),e=>e.code==='AI_MODEL_HASH_INVALID'));
test('model hash rejects a forged explicit hash',async()=>{const {service}=load();await assert.rejects(()=>service.create(7,{...input(),modelHash:'a'.repeat(64)}),e=>e.code==='AI_MODEL_HASH_MISMATCH');});
test('model registration does not allow direct ACTIVE creation',async()=>{const {service}=load();await assert.rejects(()=>service.create(7,{...input(),status:'ACTIVE'}),e=>e.code==='AI_MODEL_INITIAL_STATUS_INVALID');});
test('artifact lineage is validated when no training run is supplied',async()=>{const {service}=load({run:null,artifact:[]});await assert.rejects(()=>service.create(7,{provider:'test',modelName:'candidate',artifactId:999}),e=>e.code==='AI_MODEL_ARTIFACT_NOT_FOUND');});
test('metadata scrubs secret keys',()=>{const {service}=load();const clean=service.sanitize({api_key:'do-not-store',eval:.9});assert.equal(clean.api_key,'[REDACTED_SECRET]');assert.equal(clean.eval,.9);});
