const test=require('node:test');
const assert=require('node:assert/strict');
const Module=require('node:module');
function load(rows=[]){const original=Module._load;const calls=[];let queue=rows.slice();const db={query:async(sql,p)=>{if(sql.includes('AI_FINE_TUNE_RUN')&&sql.includes('IDEMPOTENCY_KEY'))return queue.shift()||[];if(sql.includes('AI_FINE_TUNE_ARTIFACT'))return [{ID:12,ARTIFACT_HASH:'a'.repeat(64),DATASET_HASH:'b'.repeat(64)}];if(sql.includes('RUN_HASH'))return [];return rows;},nextId:async()=>91,execute:async(sql,p)=>calls.push({sql,p}),dialect:()=>({limit:(sql,n)=>sql+' ROWS '+n})};Module._load=function(request,parent,isMain){if(request==='./db.service'&&parent?.filename?.endsWith('fine-tuning.run.service.js'))return db;return original.apply(this,arguments);};delete require.cache[require.resolve('../src/services/fine-tuning.run.service')];const service=require('../src/services/fine-tuning.run.service');Module._load=original;return{service,db,calls};}
function input(){return{artifactId:12,idempotencyKey:'run-001',provider:'test',model:'candidate-model',trainingConfig:{epochs:2},metrics:{loss:.2}};}
test('run hash is deterministic',()=>assert.equal(load().service.runHash(input()),load().service.runHash({...input(),trainingConfig:{epochs:2}})));
test('validation requires artifact and idempotency key',()=>assert.throws(()=>load().service.validate({artifactId:12}),e=>e.code==='FINE_TUNE_RUN_IDEMPOTENCY_KEY_REQUIRED'));
test('creation is idempotent by key',async()=>{const {service}=load([[{ID:50,TENANT_ID:7,ARTIFACT_ID:12,STATUS:'QUEUED',CREATED_AT:'x'}]]);const r=await service.create(7,input());assert.equal(r.idempotent,true);assert.equal(r.ID,50);});
test('creation persists artifact lineage and training metadata',async()=>{const {service,calls}=load([[],[]]);const r=await service.create(7,input());assert.equal(r.id,91);assert.equal(calls.length,1);assert.equal(calls[0].p[1],7);assert.equal(calls[0].p[2],12);assert.equal(calls[0].p[4],'run-001');assert.equal(calls[0].p[8],'QUEUED');});
