FROM node:18-bookworm-slim

WORKDIR /app

COPY backend/package.json ./package.json
RUN npm install --omit=dev && npm cache clean --force

COPY backend/src ./src

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "src/app.production.js"]
