FROM node:18

WORKDIR /app

COPY backend/package.basic.json ./package.json
COPY backend/src ./src
COPY backend/entrypoint.sh ./entrypoint.sh

RUN npm install --omit=dev

EXPOSE 3000

CMD ["node", "src/app.production.js"]
