FROM node:18

WORKDIR /app

COPY backend ./

# garantir package.json
RUN if [ -f package.basic.json ]; then cp package.basic.json package.json; fi

RUN npm install && npm install node-firebird

EXPOSE 3000

CMD ["node", "src/app.production.js"]
