const crypto=require('node:crypto');const db=require('./db.service');
const STATUSES=new Set(['RUNNING','COMPLETED','FAILED','CANCELLED']);
function fail(code,status=400){const e=new Error(code);e.code=code;e.status=status;throw e;}
function stable(v){if(v===null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(stable);return Object.keys(v).sort().reduce((o,k)=>(o[k]=stable(v[k]),o),{});}
function executionHash(i){return crypto.createHash('sha256').update(JSON.stringify(stable({tenant_id:i.tenantId,agent_name:i.agentName,skill_name:i.skillName||null,plan_id:i.planId||null,idempotency_key:i.idempotencyKey||null,plan_hash:i.planHash||null}))).digest('hex');}
function validate(i={}){if(!i.tenantId)fail('TENANT_CONTEXT_REQUIRED',401);if(!String(i.agentName||'').trim())fail('AGENT_NAME_REQUIRED');if(!String(i.correlationId||'').trim())fail('AGENT_CORRELATION_ID_REQUIRED');if(i.maxSteps!=null&&(!Number.isInteger(Number(i.maxSteps))||Number(i.maxSteps)<1||Number(i.maxSteps)>20))fail('AGENT_MAX_STEPS_INVALID');if(i.timeoutBudgetMs!=null&&(!Number.isInteger(Number(i.timeoutBudgetMs))||Number(i.timeoutBudgetMs)<1||Number(i.timeoutBudgetMs)>120000))fail('AGENT_TIMEOUT_BUDGET_INVALID');if(i.status!=null&&!STATUSES.has(String(i.status).toUpperCase()))fail('AGENT_STATUS_INVALID');return true;}
async function create(i={}){validate(i);const hash=executionHash(i);const idem=i.idempotencyKey==null?null:String(i.idempotencyKey).trim();let existing=await db.query('SELECT ID,TENANT_ID,EXECUTION_HASH,AGENT_NAME,SKILL_NAME,PLAN_ID,STATUS,STEP_COUNT,MAX_STEPS,TIMEOUT_BUDGET_MS,APPROVAL_REQUIRED,APPROVAL_ID,CORRELATION_ID,IDEMPOTENCY_KEY,CREATED_AT FROM AI_AGENT_EXECUTION WHERE TENANT_ID=? AND EXECUTION_HASH=?',[i.tenantId,hash]);if(!existing[0]&&idem)existing=await db.query('SELECT ID,TENANT_ID,EXECUTION_HASH,AGENT_NAME,SKILL_NAME,PLAN_ID,STATUS,STEP_COUNT,MAX_STEPS,TIMEOUT_BUDGET_MS,APPROVAL_REQUIRED,APPROVAL_ID,CORRELATION_ID,IDEMPOTENCY_KEY,CREATED_AT FROM AI_AGENT_EXECUTION WHERE TENANT_ID=? AND IDEMPOTENCY_KEY=?',[i.tenantId,idem]);if(existing[0])return {...existing[0],idempotent:true};const id=await db.nextId('AI_AGENT_EXECUTION');try{await db.execute('INSERT INTO AI_AGENT_EXECUTION (ID,TENANT_ID,EXECUTION_HASH,AGENT_NAME,SKILL_NAME,PLAN_ID,STATUS,STEP_COUNT,MAX_STEPS,TIMEOUT_BUDGET_MS,APPROVAL_REQUIRED,APPROVAL_ID,CORRELATION_ID,IDEMPOTENCY_KEY,CREATED_BY) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,i.tenantId,hash,String(i.agentName).trim(),i.skillName||null,i.planId||null,String(i.status||'RUNNING').toUpperCase(),0,Number(i.maxSteps||3),Number(i.timeoutBudgetMs||15000),i.approvalRequired?1:0,i.approvalId||null,String(i.correlationId).trim(),idem,i.createdBy||null]);}catch(error){existing=await db.query('SELECT ID,TENANT_ID,EXECUTION_HASH,AGENT_NAME,SKILL_NAME,PLAN_ID,STATUS,STEP_COUNT,MAX_STEPS,TIMEOUT_BUDGET_MS,APPROVAL_REQUIRED,APPROVAL_ID,CORRELATION_ID,IDEMPOTENCY_KEY,CREATED_AT FROM AI_AGENT_EXECUTION WHERE TENANT_ID=? AND EXECUTION_HASH=?',[i.tenantId,hash]);if(!existing[0]&&idem)existing=await db.query('SELECT ID,TENANT_ID,EXECUTION_HASH,AGENT_NAME,SKILL_NAME,PLAN_ID,STATUS,STEP_COUNT,MAX_STEPS,TIMEOUT_BUDGET_MS,APPROVAL_REQUIRED,APPROVAL_ID,CORRELATION_ID,IDEMPOTENCY_KEY,CREATED_AT FROM AI_AGENT_EXECUTION WHERE TENANT_ID=? AND IDEMPOTENCY_KEY=?',[i.tenantId,idem]);if(existing[0])return {...existing[0],idempotent:true};throw error;}return{id:Number(id),execution_hash:hash,status:String(i.status||'RUNNING').toUpperCase(),idempotent:false};}
async function get(tenantId,id){const rows=await db.query('SELECT ID,TENANT_ID,EXECUTION_HASH,AGENT_NAME,SKILL_NAME,PLAN_ID,STATUS,STEP_COUNT,MAX_STEPS,TIMEOUT_BUDGET_MS,APPROVAL_REQUIRED,APPROVAL_ID,CORRELATION_ID,IDEMPOTENCY_KEY,CREATED_BY,CREATED_AT,FINISHED_AT FROM AI_AGENT_EXECUTION WHERE TENANT_ID=? AND ID=?',[tenantId,Number(id)]);return rows[0]||null;}
async function advance(tenantId,id,stepCount){const row=await get(tenantId,id);if(!row)fail('AGENT_EXECUTION_NOT_FOUND',404);const n=Number(stepCount);if(!Number.isInteger(n)||n<0)fail('AGENT_STEP_COUNT_INVALID');if(n>Number(row.MAX_STEPS))fail('AGENT_STEP_BUDGET_EXCEEDED',409);if(String(row.STATUS).toUpperCase()!=='RUNNING')fail('AGENT_EXECUTION_NOT_RUNNING',409);await db.execute('UPDATE AI_AGENT_EXECUTION SET STEP_COUNT=? WHERE TENANT_ID=? AND ID=? AND STATUS=?',[n,tenantId,Number(id),'RUNNING']);return get(tenantId,id);}
async function finish(tenantId,id,status){const next=String(status||'').toUpperCase();if(!['COMPLETED','FAILED','CANCELLED'].includes(next))fail('AGENT_TERMINAL_STATUS_INVALID');const row=await get(tenantId,id);if(!row)fail('AGENT_EXECUTION_NOT_FOUND',404);if(String(row.STATUS).toUpperCase()!=='RUNNING'&&String(row.STATUS).toUpperCase()!==next)fail('AGENT_EXECUTION_NOT_RUNNING',409);await db.execute('UPDATE AI_AGENT_EXECUTION SET STATUS=?,FINISHED_AT=CURRENT_TIMESTAMP WHERE TENANT_ID=? AND ID=? AND STATUS=?',[next,tenantId,Number(id),'RUNNING']);return get(tenantId,id);}
module.exports={STATUSES,stable,executionHash,validate,create,get,advance,finish};