const crypto=require('node:crypto');
const db=require('./db.service');
const STATUSES=new Set(['REGISTERED','VALIDATED','CANARY','ACTIVE','RETIRED','REJECTED']);
const HEX64=/^[a-f0-9]{64}$/i;
function fail(code,status=400){const e=new Error(code);e.code=code;e.status=status;throw e;}
function stable(v){if(v===null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(stable);return Object.keys(v).sort().reduce((o,k)=>(o[k]=stable(v[k]),o),{});}
function modelHash(input){return crypto.createHash('sha256').update(JSON.stringify(stable({provider:input.provider,modelName:input.modelName,modelVersion:input.modelVersion||null,modelUri:input.modelUri||null,runId:input.runId||null,artifactId:input.artifactId||null,metadata:input.metadata||{}}))).digest('hex');}
function validate(i={}){if(!String(i.provider||'').trim())fail('AI_MODEL_PROVIDER_REQUIRED');if(!String(i.modelName||'').trim())fail('AI_MODEL_NAME_REQUIRED');if(i.runId!=null&&(!Number.isInteger(Number(i.runId))||Number(i.runId)<=0))fail('AI_MODEL_RUN_ID_INVALID');if(i.artifactId!=null&&(!Number.isInteger(Number(i.artifactId))||Number(i.artifactId)<=0))fail('AI_MODEL_ARTIFACT_ID_INVALID');if(i.status!=null&&!STATUSES.has(String(i.status).toUpperCase()))fail('AI_MODEL_STATUS_INVALID');if(i.modelHash!=null&&!HEX64.test(String(i.modelHash)))fail('AI_MODEL_HASH_INVALID');return true;}
async function create(tenantId,input={}){validate(input);if(input.runId!=null){const run=await db.query('SELECT ID,ARTIFACT_ID,STATUS,PROVIDER,MODEL FROM AI_FINE_TUNE_RUN WHERE TENANT_ID=? AND ID=?',[tenantId,Number(input.runId)]);if(!run[0])fail('AI_MODEL_TRAINING_RUN_NOT_FOUND',404);if(!['COMPLETED'].includes(String(run[0].STATUS).toUpperCase()))fail('AI_MODEL_TRAINING_RUN_NOT_COMPLETED',409);if(input.artifactId!=null&&Number(input.artifactId)!==Number(run[0].ARTIFACT_ID))fail('AI_MODEL_ARTIFACT_MISMATCH',409);input.artifactId=run[0].ARTIFACT_ID;}
 const hash=input.modelHash||modelHash(input);const existing=await db.query('SELECT ID,TENANT_ID,MODEL_HASH,STATUS,CREATED_AT FROM AI_MODEL_VERSION WHERE TENANT_ID=? AND MODEL_HASH=?',[tenantId,hash]);if(existing[0])return {...existing[0],idempotent:true};
 const id=await db.nextId('AI_MODEL_VERSION');await db.execute('INSERT INTO AI_MODEL_VERSION (ID,TENANT_ID,MODEL_HASH,RUN_ID,ARTIFACT_ID,PROVIDER,MODEL_NAME,MODEL_VERSION,MODEL_URI,STATUS,METADATA_JSON,CREATED_BY) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[id,tenantId,hash,input.runId==null?null:Number(input.runId),input.artifactId==null?null:Number(input.artifactId),String(input.provider).trim(),String(input.modelName).trim(),input.modelVersion||null,input.modelUri||null,String(input.status||'REGISTERED').toUpperCase(),JSON.stringify(stable(input.metadata||{})),input.createdBy||null]);return{id:Number(id),tenant_id:tenantId,model_hash:hash,status:String(input.status||'REGISTERED').toUpperCase(),idempotent:false};}
async function get(tenantId,id){const r=await db.query('SELECT ID,TENANT_ID,MODEL_HASH,RUN_ID,ARTIFACT_ID,PROVIDER,MODEL_NAME,MODEL_VERSION,MODEL_URI,STATUS,METADATA_JSON,CREATED_BY,CREATED_AT FROM AI_MODEL_VERSION WHERE TENANT_ID=? AND ID=?',[tenantId,Number(id)]);return r[0]||null;}
async function list(tenantId,limit=50){const n=Math.min(Math.max(Number(limit||50),1),100);return db.query(db.dialect().limit('SELECT ID,MODEL_HASH,RUN_ID,ARTIFACT_ID,PROVIDER,MODEL_NAME,MODEL_VERSION,STATUS,CREATED_BY,CREATED_AT FROM AI_MODEL_VERSION WHERE TENANT_ID=? ORDER BY CREATED_AT DESC,ID DESC',n),[tenantId]);}
module.exports={STATUSES,stable,modelHash,validate,create,get,list};
