const db=require('./db.service');
async function nextId(){return db.nextId('AI_PROMPT_VERSION');}
async function list(tenantId){return db.query("SELECT ID,TENANT_ID,VERSION_NO,NAME,PROMPT_JSON,STATUS,CREATED_AT,PROMOTED_AT FROM AI_PROMPT_VERSION WHERE TENANT_ID=? OR TENANT_ID IS NULL ORDER BY VERSION_NO DESC",[tenantId]);}
async function create(input){const id=await nextId();await db.execute('INSERT INTO AI_PROMPT_VERSION (ID,TENANT_ID,VERSION_NO,NAME,PROMPT_JSON,STATUS) VALUES (?,?,?,?,?,?)',[id,input.tenantId||null,input.versionNo,input.name,JSON.stringify(input.prompt),input.status||'DRAFT']);return id;}
async function getById(tenantId,id){const rows=await db.query("SELECT ID,TENANT_ID,VERSION_NO,NAME,PROMPT_JSON,STATUS FROM AI_PROMPT_VERSION WHERE ID=? AND (TENANT_ID=? OR TENANT_ID IS NULL)",[id,tenantId]);if(!rows[0]){const e=new Error('PROMPT_VERSION_NOT_FOUND');e.status=404;throw e;}return rows[0];}
async function promotionGate(tenantId,id){const candidate=await getById(tenantId,id);const runs=await db.query('SELECT SCORE,DETAILS_JSON FROM AI_EVAL_RUN WHERE TENANT_ID=? AND CREATED_AT >= ?',[tenantId,new Date(Date.now()-86400000).toISOString()]);const candidateRuns=runs.filter((row)=>{try{const d=typeof row.DETAILS_JSON==='string'?JSON.parse(row.DETAILS_JSON):row.DETAILS_JSON;return Number(d?.candidate_prompt_version_id)===Number(id);}catch{return false;}});const score=candidateRuns.length?candidateRuns.reduce((sum,row)=>sum+Number(row.SCORE||0),0)/candidateRuns.length:null;const min=Number(process.env.AI_PROMOTION_MIN_SCORE||0.8);if(score==null||score<min){const e=new Error('PROMOTION_POLICY_NOT_MET');e.status=409;e.details={version:Number(candidate.VERSION_NO),prompt_version_id:Number(id),score,min_score:min,eval_count:candidateRuns.length};throw e;}return{version:Number(candidate.VERSION_NO),prompt_version_id:Number(id),score,min_score:min,eval_count:Number(runs[0]?.COUNT||0)};}
async function promote(tenantId,id){return db.withTransaction(async tx=>{const current=await tx.query("SELECT ID FROM AI_PROMPT_VERSION WHERE TENANT_ID=? AND STATUS='ACTIVE'",[tenantId]);await tx.execute("UPDATE AI_PROMPT_VERSION SET STATUS='RETIRED' WHERE TENANT_ID=? AND STATUS='ACTIVE'",[tenantId]);const rows=await tx.query("SELECT ID,VERSION_NO FROM AI_PROMPT_VERSION WHERE ID=? AND (TENANT_ID=? OR TENANT_ID IS NULL)",[id,tenantId]);if(!rows[0]){const e=new Error('PROMPT_VERSION_NOT_FOUND');e.status=404;throw e;}await tx.execute("UPDATE AI_PROMPT_VERSION SET STATUS='ACTIVE',PROMOTED_AT=CURRENT_TIMESTAMP WHERE ID=?",[id]);return{promoted_id:Number(id),previous_active:current[0]?.ID?Number(current[0].ID):null,version_no:Number(rows[0].VERSION_NO)};});}
async function resolve(tenantId){const rows=await db.query("SELECT ID,VERSION_NO,PROMPT_JSON,STATUS FROM AI_PROMPT_VERSION WHERE (TENANT_ID=? OR TENANT_ID IS NULL) AND STATUS='ACTIVE' ORDER BY TENANT_ID DESC,VERSION_NO DESC",[tenantId]);return rows[0]||null;}
async function resolveById(tenantId,id){return getById(tenantId,id);}
module.exports={list,create,promote,promotionGate,resolve,resolveById};