const db=require('./db.service');
async function nextId(){return db.nextId('AI_PROMPT_VERSION');}
function rowQuery(tx,tenantId,id){return tx.query("SELECT ID,TENANT_ID,VERSION_NO,NAME,PROMPT_JSON,STATUS FROM AI_PROMPT_VERSION WHERE ID=? AND (TENANT_ID=? OR TENANT_ID IS NULL)",[id,tenantId]);}
async function list(tenantId){return db.query("SELECT ID,TENANT_ID,VERSION_NO,NAME,PROMPT_JSON,STATUS,CREATED_AT,PROMOTED_AT FROM AI_PROMPT_VERSION WHERE TENANT_ID=? OR TENANT_ID IS NULL ORDER BY VERSION_NO DESC",[tenantId]);}
async function create(input){const id=await nextId();await db.execute('INSERT INTO AI_PROMPT_VERSION (ID,TENANT_ID,VERSION_NO,NAME,PROMPT_JSON,STATUS) VALUES (?,?,?,?,?,?)',[id,input.tenantId||null,input.versionNo,input.name,JSON.stringify(input.prompt),input.status||'DRAFT']);return id;}
async function createTx(tx,input){const id=await tx.nextId('AI_PROMPT_VERSION');await tx.execute('INSERT INTO AI_PROMPT_VERSION (ID,TENANT_ID,VERSION_NO,NAME,PROMPT_JSON,STATUS) VALUES (?,?,?,?,?,?)',[id,input.tenantId||null,input.versionNo,input.name,JSON.stringify(input.prompt),input.status||'DRAFT']);return id;}
async function getById(tenantId,id){const rows=await rowQuery(db,tenantId,id);if(!rows[0]){const e=new Error('PROMPT_VERSION_NOT_FOUND');e.status=404;throw e;}return rows[0];}
async function getByIdTx(tx,tenantId,id){const rows=await rowQuery(tx,tenantId,id);if(!rows[0]){const e=new Error('PROMPT_VERSION_NOT_FOUND');e.status=404;throw e;}return rows[0];}
async function evaluationGate(tenantId,id){const candidate=await getById(tenantId,id);const active=await resolve(tenantId);const since=new Date(Date.now()-86400000);const rows=await db.query('SELECT SCORE,PROMPT_VERSION_ID,BASELINE_PROMPT_VERSION_ID,CREATED_AT FROM AI_EVAL_RUN WHERE TENANT_ID=? AND CREATED_AT >= ?',[tenantId,since]);function versionOf(row){return row.PROMPT_VERSION_ID==null?null:Number(row.PROMPT_VERSION_ID);}function average(items){return items.length?items.reduce((sum,row)=>sum+Number(row.SCORE||0),0)/items.length:null;}const candidateRuns=rows.filter(r=>versionOf(r)===Number(id));const baselineId=active?.ID?Number(active.ID):null;const baselineRuns=baselineId?rows.filter(r=>versionOf(r)===baselineId):[];const candidateScore=average(candidateRuns);const baselineScore=average(baselineRuns);const min=Number(process.env.AI_PROMOTION_MIN_SCORE||0.8);const minDelta=Number(process.env.AI_PROMOTION_MIN_DELTA||0);const minEvals=Math.max(Number(process.env.AI_PROMOTION_MIN_EVALS||3),1);const delta=candidateScore==null||baselineScore==null?null:Number((candidateScore-baselineScore).toFixed(4));const meetsMinimum=candidateScore!=null&&candidateScore>=min;const hasEnoughEvaluations=candidateRuns.length>=minEvals;const beatsBaseline=baselineScore==null||delta>=minDelta;if(!meetsMinimum||!hasEnoughEvaluations||!beatsBaseline){const e=new Error('PROMOTION_POLICY_NOT_MET');e.status=409;e.details={version:Number(candidate.VERSION_NO),prompt_version_id:Number(id),candidate_score:candidateScore,baseline_prompt_version_id:baselineId,baseline_score:baselineScore,delta,min_score:min,min_delta:minDelta,candidate_eval_count:candidateRuns.length,baseline_eval_count:baselineRuns.length,min_eval_count:minEvals};throw e;}return{version:Number(candidate.VERSION_NO),prompt_version_id:Number(id),baseline_prompt_version_id:baselineId,candidate_score:candidateScore,baseline_score:baselineScore,delta,min_score:min,min_delta:minDelta,candidate_eval_count:candidateRuns.length,baseline_eval_count:baselineRuns.length,min_eval_count:minEvals};}
async function promotionGate(tenantId,id){const gate=await evaluationGate(tenantId,id);const releaseRows=await db.query("SELECT ID,STATUS,RESULT_JSON FROM AI_PROMPT_RELEASE WHERE TENANT_ID=? AND PROMPT_VERSION_ID=? ORDER BY STARTED_AT DESC,ID DESC",[tenantId,Number(id)]);const passed=releaseRows.find(r=>String(r.STATUS).toUpperCase()==='PASSED');if(!passed){const e=new Error('PROMOTION_POLICY_NOT_MET');e.status=409;e.details={...gate,canary_passed:false};throw e;}return{...gate,canary_passed:true,canary_release_id:Number(passed.ID)};}
async function promote(tenantId,id,meta={}){const candidate=await getById(tenantId,id);if(Number(candidate.TENANT_ID)!==Number(tenantId)){const e=new Error('PROMPT_VERSION_TENANT_MISMATCH');e.status=409;throw e;}if(String(candidate.STATUS)==='ACTIVE')return{promoted_id:Number(id),previous_active:Number(id),version_no:Number(candidate.VERSION_NO),idempotent:true};const gate=await promotionGate(tenantId,id);return db.withTransaction(async tx=>{const current=await tx.query("SELECT ID FROM AI_PROMPT_VERSION WHERE TENANT_ID=? AND STATUS='ACTIVE'",[tenantId]);await tx.execute("UPDATE AI_PROMPT_VERSION SET STATUS='RETIRED' WHERE TENANT_ID=? AND STATUS='ACTIVE'",[tenantId]);const rows=await tx.query("SELECT ID,VERSION_NO FROM AI_PROMPT_VERSION WHERE ID=? AND (TENANT_ID=? OR TENANT_ID IS NULL)",[id,tenantId]);if(!rows[0]){const e=new Error('PROMPT_VERSION_NOT_FOUND');e.status=404;throw e;}await tx.execute("UPDATE AI_PROMPT_VERSION SET STATUS='ACTIVE',PROMOTED_AT=CURRENT_TIMESTAMP WHERE ID=?",[id]);const auditId=await tx.nextId('AI_PROMPT_PROMOTION_AUDIT');await tx.execute("INSERT INTO AI_PROMPT_PROMOTION_AUDIT (ID,TENANT_ID,PROMPT_VERSION_ID,BASELINE_VERSION_ID,RELEASE_ID,EVAL_RUN_COUNT,CANDIDATE_SCORE,BASELINE_SCORE,DELTA,CANARY_STATUS,DECISION,DECIDED_BY,CORRELATION_ID,REASON,DETAILS_JSON) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[auditId,tenantId,Number(id),gate.baseline_prompt_version_id||null,gate.canary_release_id||null,gate.candidate_eval_count||0,gate.candidate_score,gate.baseline_score,gate.delta,'PASSED','PROMOTED',meta.decidedBy||null,meta.correlationId||null,meta.reason||'promotion policy passed',JSON.stringify(gate)]);return{promoted_id:Number(id),previous_active:current[0]?.ID?Number(current[0].ID):null,version_no:Number(rows[0].VERSION_NO),promotion_audit_id:Number(auditId),gate};});}
async function rollback(tenantId,targetId,meta={}) {
 const target=await getById(tenantId,Number(targetId));
 if(Number(target.TENANT_ID)!==Number(tenantId)){const e=new Error('PROMPT_VERSION_TENANT_MISMATCH');e.status=409;throw e;}
 if(String(target.STATUS).toUpperCase()==='ACTIVE') return {rolled_back_to:Number(targetId),previous_active:Number(targetId),idempotent:true};
 return db.withTransaction(async tx=>{
  const lock=(sql)=>typeof db.dialect==='function'&&typeof db.dialect().lock==='function'?db.dialect().lock(sql):sql;
  const current=await tx.query(lock("SELECT ID,VERSION_NO FROM AI_PROMPT_VERSION WHERE TENANT_ID=? AND STATUS='ACTIVE'"),[tenantId]);
  if(!current[0]){const e=new Error('ACTIVE_PROMPT_NOT_FOUND');e.status=409;throw e;}
  const targetRows=await tx.query(lock("SELECT ID,VERSION_NO,STATUS FROM AI_PROMPT_VERSION WHERE ID=? AND TENANT_ID=?"),[Number(targetId),tenantId]);
  if(!targetRows[0]){const e=new Error('PROMPT_VERSION_NOT_FOUND');e.status=404;throw e;}
  if(String(targetRows[0].STATUS).toUpperCase()!=='RETIRED'){const e=new Error('PROMPT_ROLLBACK_TARGET_NOT_RETIRED');e.status=409;throw e;}
  await tx.execute("UPDATE AI_PROMPT_VERSION SET STATUS='RETIRED' WHERE TENANT_ID=? AND STATUS='ACTIVE'",[tenantId]);
  await tx.execute("UPDATE AI_PROMPT_VERSION SET STATUS='ACTIVE',PROMOTED_AT=CURRENT_TIMESTAMP WHERE ID=? AND TENANT_ID=?",[Number(targetId),tenantId]);
  const auditId=await tx.nextId('AI_PROMPT_PROMOTION_AUDIT');
  await tx.execute("INSERT INTO AI_PROMPT_PROMOTION_AUDIT (ID,TENANT_ID,PROMPT_VERSION_ID,BASELINE_VERSION_ID,RELEASE_ID,EVAL_RUN_COUNT,CANDIDATE_SCORE,BASELINE_SCORE,DELTA,CANARY_STATUS,DECISION,DECIDED_BY,CORRELATION_ID,REASON,DETAILS_JSON) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[auditId,tenantId,Number(targetId),Number(current[0].ID),null,0,null,null,null,'NOT_APPLICABLE','ROLLED_BACK',meta.decidedBy||null,meta.correlationId||null,meta.reason||'production prompt rollback',JSON.stringify({from_prompt_version_id:Number(current[0].ID),to_prompt_version_id:Number(targetId)})]);
  return {rolled_back_to:Number(targetId),previous_active:Number(current[0].ID),version_no:Number(targetRows[0].VERSION_NO),promotion_audit_id:Number(auditId)};
 });
}
async function promotionHistory(tenantId,id,limit=50){const n=Math.min(Math.max(Number(limit||50),1),100);const sql=db.dialect().limit('SELECT ID,PROMPT_VERSION_ID,BASELINE_VERSION_ID,RELEASE_ID,EVAL_RUN_COUNT,CANDIDATE_SCORE,BASELINE_SCORE,DELTA,CANARY_STATUS,DECISION,DECIDED_BY,DECIDED_AT,CORRELATION_ID,REASON,DETAILS_JSON FROM AI_PROMPT_PROMOTION_AUDIT WHERE TENANT_ID=? AND PROMPT_VERSION_ID=? ORDER BY DECIDED_AT DESC,ID DESC',n);return db.query(sql,[tenantId,Number(id)]);}
async function resolve(tenantId){const rows=await db.query("SELECT ID,VERSION_NO,PROMPT_JSON,STATUS FROM AI_PROMPT_VERSION WHERE (TENANT_ID=? OR TENANT_ID IS NULL) AND STATUS='ACTIVE' ORDER BY TENANT_ID DESC,VERSION_NO DESC",[tenantId]);return rows[0]||null;}
async function resolveTx(tx,tenantId){const rows=await tx.query("SELECT ID,VERSION_NO,PROMPT_JSON,STATUS FROM AI_PROMPT_VERSION WHERE (TENANT_ID=? OR TENANT_ID IS NULL) AND STATUS='ACTIVE' ORDER BY TENANT_ID DESC,VERSION_NO DESC",[tenantId]);return rows[0]||null;}
async function resolveById(tenantId,id){return getById(tenantId,id);}
async function resolveByIdTx(tx,tenantId,id){return getByIdTx(tx,tenantId,id);}
module.exports={list,create,createTx,promote,rollback,promotionHistory,evaluationGate,promotionGate,resolve,resolveTx,resolveById,resolveByIdTx};
