const crypto=require('node:crypto');
const db=require('./db.service');
const HEX64=/^[a-f0-9]{64}$/i;
function fail(code,status=400){const e=new Error(code);e.code=code;e.status=status;throw e;}
function stable(value){if(value===null||typeof value!=='object')return value;if(Array.isArray(value))return value.map(stable);return Object.keys(value).sort().reduce((o,k)=>{o[k]=stable(value[k]);return o;},{});}
function artifactHash(input){const manifest=stable({dataset_hash:String(input.datasetHash||''),dataset_version:Number(input.datasetVersion||1),examples_count:Number(input.examplesCount||0),train_count:Number(input.trainCount||0),validation_count:Number(input.validationCount||0),validation_ratio:input.validationRatio==null?null:Number(input.validationRatio),prompt_version_id:input.promptVersionId==null?null:Number(input.promptVersionId),baseline_prompt_version_id:input.baselinePromptVersionId==null?null:Number(input.baselinePromptVersionId),model:input.model||null,provider:input.provider||null,training_config:stable(input.trainingConfig||{}),lineage:stable(input.lineage||{})});return crypto.createHash('sha256').update(JSON.stringify(manifest)).digest('hex');}
function validate(input={}){if(!HEX64.test(String(input.datasetHash||'')))fail('FINE_TUNE_DATASET_HASH_REQUIRED');const counts=['examplesCount','trainCount','validationCount'];for(const key of counts)if(!Number.isInteger(Number(input[key]))||Number(input[key])<0)fail('FINE_TUNE_DATASET_COUNT_INVALID');const total=Number(input.trainCount)+Number(input.validationCount);if(total!==Number(input.examplesCount))fail('FINE_TUNE_DATASET_SPLIT_MISMATCH');if(input.validationRatio!=null&&(!Number.isFinite(Number(input.validationRatio))||Number(input.validationRatio)<0||Number(input.validationRatio)>=1))fail('FINE_TUNE_VALIDATION_RATIO_INVALID');return true;}
async function create(tenantId,input={}){validate(input);const hash=artifactHash(input);const existing=await db.query('SELECT ID,ARTIFACT_HASH,DATASET_HASH,STATUS,CREATED_AT FROM AI_FINE_TUNE_ARTIFACT WHERE TENANT_ID=? AND ARTIFACT_HASH=?',[tenantId,hash]);if(existing[0])return{...existing[0],idempotent:true};const id=await db.nextId('AI_FINE_TUNE_ARTIFACT');await db.execute('INSERT INTO AI_FINE_TUNE_ARTIFACT (ID,TENANT_ID,ARTIFACT_HASH,DATASET_HASH,DATASET_VERSION,EXAMPLES_COUNT,TRAIN_COUNT,VALIDATION_COUNT,VALIDATION_RATIO,PROMPT_VERSION_ID,BASELINE_PROMPT_VERSION_ID,MODEL,PROVIDER,TRAINING_CONFIG_JSON,LINEAGE_JSON,STATUS,CREATED_BY) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,tenantId,hash,input.datasetHash,Number(input.datasetVersion||1),Number(input.examplesCount),Number(input.trainCount),Number(input.validationCount),input.validationRatio==null?null:Number(input.validationRatio),input.promptVersionId==null?null:Number(input.promptVersionId),input.baselinePromptVersionId==null?null:Number(input.baselinePromptVersionId),input.model||null,input.provider||null,JSON.stringify(stable(input.trainingConfig||{})),JSON.stringify(stable(input.lineage||{})),String(input.status||'READY').toUpperCase(),input.createdBy||null]);return{id:Number(id),artifact_hash:hash,dataset_hash:input.datasetHash,status:String(input.status||'READY').toUpperCase(),idempotent:false};}
async function get(tenantId,id){const rows=await db.query('SELECT ID,TENANT_ID,ARTIFACT_HASH,DATASET_HASH,DATASET_VERSION,EXAMPLES_COUNT,TRAIN_COUNT,VALIDATION_COUNT,VALIDATION_RATIO,PROMPT_VERSION_ID,BASELINE_PROMPT_VERSION_ID,MODEL,PROVIDER,TRAINING_CONFIG_JSON,LINEAGE_JSON,STATUS,CREATED_BY,CREATED_AT FROM AI_FINE_TUNE_ARTIFACT WHERE TENANT_ID=? AND ID=?',[tenantId,Number(id)]);return rows[0]||null;}
async function list(tenantId,limit=50){const n=Math.min(Math.max(Number(limit||50),1),100);return db.query(db.dialect().limit('SELECT ID,ARTIFACT_HASH,DATASET_HASH,DATASET_VERSION,EXAMPLES_COUNT,TRAIN_COUNT,VALIDATION_COUNT,PROMPT_VERSION_ID,BASELINE_PROMPT_VERSION_ID,MODEL,PROVIDER,STATUS,CREATED_BY,CREATED_AT FROM AI_FINE_TUNE_ARTIFACT WHERE TENANT_ID=? ORDER BY CREATED_AT DESC,ID DESC',n),[tenantId]);}
module.exports={stable,artifactHash,validate,create,get,list};
