CREATE TABLE SYNC_CONFLICT (
    ID BIGINT NOT NULL,
    TABELA VARCHAR(50),
    CHAVE VARCHAR(100),
    PAYLOAD_ORIGEM BLOB SUB_TYPE TEXT,
    PAYLOAD_DESTINO BLOB SUB_TYPE TEXT,
    DATA_CONFLITO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESOLVIDO CHAR(1) DEFAULT 'N'
);

ALTER TABLE SYNC_CONFLICT ADD CONSTRAINT PK_SYNC_CONFLICT PRIMARY KEY (ID);

CREATE GENERATOR GEN_SYNC_CONFLICT_ID;

SET TERM !! ;
CREATE TRIGGER BI_SYNC_CONFLICT FOR SYNC_CONFLICT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SYNC_CONFLICT_ID, 1);
END!!
SET TERM ; !!