ALTER TABLE INTEGRATION_DEVICE ADD CREDENTIAL_HASH VARCHAR(128);
ALTER TABLE INTEGRATION_DEVICE ADD CREDENTIAL_CREATED_AT TIMESTAMP;
ALTER TABLE INTEGRATION_DEVICE ADD CREDENTIAL_EXPIRES_AT TIMESTAMP;
ALTER TABLE INTEGRATION_DEVICE ADD CREDENTIAL_VERSION INTEGER DEFAULT 1 NOT NULL;
CREATE INDEX IDX_DEVICE_CREDENTIAL_HASH ON INTEGRATION_DEVICE (CREDENTIAL_HASH);
