CREATE TABLE TENANT (
    ID INTEGER,
    NOME VARCHAR(100),
    API_KEY VARCHAR(100),
    STATUS CHAR(1)
);

CREATE TABLE SYNC_LOG (
    ID BIGINT,
    EMPRESA_ID INTEGER,
    TABELA VARCHAR(50),
    CHAVE VARCHAR(100),
    OPERACAO CHAR(1),
    DATA TIMESTAMP,
    HASH_UNICO VARCHAR(64)
);

CREATE TABLE SYNC_STAGING (
    ID BIGINT,
    EMPRESA_ID INTEGER,
    PAYLOAD BLOB SUB_TYPE TEXT,
    STATUS CHAR(1)
);

CREATE TABLE ASSINATURA (
    ID INTEGER,
    TENANT_ID INTEGER,
    STATUS CHAR(1),
    DATA_VENCIMENTO DATE
);

CREATE TABLE AUDIT_LOG (
    ID BIGINT,
    USUARIO_ID INTEGER,
    ACAO VARCHAR(20),
    TABELA VARCHAR(50),
    DATA TIMESTAMP
);
