CREATE TABLE TENANT (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    API_KEY VARCHAR(100) NOT NULL,
    STATUS CHAR(1) DEFAULT 'A' NOT NULL
);
ALTER TABLE TENANT ADD CONSTRAINT PK_TENANT PRIMARY KEY (ID);
CREATE UNIQUE INDEX UQ_TENANT_API_KEY ON TENANT (API_KEY);

CREATE TABLE SYNC_LOG (
    ID BIGINT NOT NULL,
    EMPRESA_ID INTEGER NOT NULL,
    TABELA VARCHAR(50) NOT NULL,
    CHAVE VARCHAR(100) NOT NULL,
    OPERACAO CHAR(1) NOT NULL,
    DATA TIMESTAMP NOT NULL,
    HASH_UNICO VARCHAR(64)
);
ALTER TABLE SYNC_LOG ADD CONSTRAINT PK_SYNC_LOG PRIMARY KEY (ID);
CREATE INDEX IDX_SYNC_LOG_DATA_ID ON SYNC_LOG (DATA, ID);

CREATE TABLE SYNC_STAGING (
    ID BIGINT NOT NULL,
    EMPRESA_ID INTEGER NOT NULL,
    TABELA VARCHAR(50) NOT NULL,
    CHAVE VARCHAR(100),
    OPERACAO CHAR(1) NOT NULL,
    PAYLOAD BLOB SUB_TYPE TEXT NOT NULL,
    DATA_RECEBIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PROCESSADO CHAR(1) DEFAULT 'N' NOT NULL,
    TENTATIVAS INTEGER DEFAULT 0 NOT NULL,
    STATUS CHAR(1) DEFAULT 'N' NOT NULL,
    HASH_UNICO VARCHAR(64),
    DATA_PROCESSAMENTO TIMESTAMP,
    WORKER_ID VARCHAR(100)
);
ALTER TABLE SYNC_STAGING ADD CONSTRAINT PK_SYNC_STAGING PRIMARY KEY (ID);
CREATE GENERATOR GEN_SYNC_STAGING_ID;
SET TERM !! ;
CREATE TRIGGER BI_SYNC_STAGING FOR SYNC_STAGING
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_SYNC_STAGING_ID, 1);
END!!
SET TERM ; !!
CREATE INDEX IDX_SYNC_STAGING_STATUS ON SYNC_STAGING (STATUS);
CREATE INDEX IDX_SYNC_STAGING_EMPRESA ON SYNC_STAGING (EMPRESA_ID, STATUS, ID);
CREATE INDEX IDX_SYNC_STAGING_RECOVERY ON SYNC_STAGING (STATUS, DATA_PROCESSAMENTO);
CREATE UNIQUE INDEX UQ_SYNC_STAGING_HASH ON SYNC_STAGING (EMPRESA_ID, HASH_UNICO);

-- Device integrations and technical audit evidence.
CREATE TABLE LEGAL_EVENT_LOG (
    ID BIGINT NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    USUARIO_ID INTEGER,
    DEVICE_ID VARCHAR(100),
    EVENT_ID VARCHAR(100) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    ACAO VARCHAR(50) NOT NULL,
    RECURSO VARCHAR(100),
    RECURSO_CHAVE VARCHAR(150),
    SERVER_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLIENT_TIMESTAMP TIMESTAMP,
    CORRELATION_ID VARCHAR(100),
    PREVIOUS_HASH VARCHAR(64),
    EVENT_HASH VARCHAR(64) NOT NULL,
    RESULTADO VARCHAR(30) NOT NULL,
    METADATA BLOB SUB_TYPE TEXT,
    PAYLOAD_HASH VARCHAR(64)
);
ALTER TABLE LEGAL_EVENT_LOG ADD CONSTRAINT PK_LEGAL_EVENT_LOG PRIMARY KEY (ID);
CREATE GENERATOR GEN_LEGAL_EVENT_LOG_ID;
SET TERM !! ;
CREATE TRIGGER BI_LEGAL_EVENT_LOG FOR LEGAL_EVENT_LOG ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_LEGAL_EVENT_LOG_ID, 1);
END!!
SET TERM ; !!
CREATE UNIQUE INDEX UQ_LEGAL_EVENT_EVENT_ID ON LEGAL_EVENT_LOG (TENANT_ID, EVENT_ID);
CREATE INDEX IDX_LEGAL_EVENT_TIME ON LEGAL_EVENT_LOG (TENANT_ID, SERVER_TIMESTAMP, ID);
CREATE INDEX IDX_LEGAL_EVENT_DEVICE ON LEGAL_EVENT_LOG (TENANT_ID, DEVICE_ID, SERVER_TIMESTAMP);
CREATE INDEX IDX_LEGAL_EVENT_CORRELATION ON LEGAL_EVENT_LOG (CORRELATION_ID);
CREATE INDEX IDX_LEGAL_EVENT_HASH ON LEGAL_EVENT_LOG (EVENT_HASH);

CREATE TABLE INTEGRATION_DEVICE (
    ID BIGINT NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    DEVICE_ID VARCHAR(100) NOT NULL,
    DEVICE_TYPE VARCHAR(30) NOT NULL,
    NAME VARCHAR(100),
    STATUS CHAR(1) DEFAULT 'A' NOT NULL,
    PROTOCOL_VERSION INTEGER DEFAULT 1 NOT NULL,
    LAST_SEEN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREDENTIAL_HASH VARCHAR(64),
    CREDENTIAL_CREATED_AT TIMESTAMP,
    CREDENTIAL_EXPIRES_AT TIMESTAMP,
    CREDENTIAL_VERSION INTEGER DEFAULT 1 NOT NULL,
    SCOPES VARCHAR(500)
);
ALTER TABLE INTEGRATION_DEVICE ADD CONSTRAINT PK_INTEGRATION_DEVICE PRIMARY KEY (ID);
CREATE GENERATOR GEN_INTEGRATION_DEVICE_ID;
SET TERM !! ;
CREATE TRIGGER BI_INTEGRATION_DEVICE FOR INTEGRATION_DEVICE ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_INTEGRATION_DEVICE_ID, 1);
END!!
SET TERM ; !!
CREATE UNIQUE INDEX UQ_DEVICE_TENANT_ID ON INTEGRATION_DEVICE (TENANT_ID, DEVICE_ID);
CREATE INDEX IDX_DEVICE_STATUS ON INTEGRATION_DEVICE (TENANT_ID, STATUS);

CREATE TABLE ASSINATURA (
    ID INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    STATUS CHAR(1) DEFAULT 'A' NOT NULL,
    DATA_VENCIMENTO DATE
);
ALTER TABLE ASSINATURA ADD CONSTRAINT PK_ASSINATURA PRIMARY KEY (ID);

CREATE TABLE AUDIT_LOG (
    ID BIGINT NOT NULL,
    USUARIO_ID INTEGER,
    ACAO VARCHAR(50) NOT NULL,
    TABELA VARCHAR(50),
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE AUDIT_LOG ADD CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ID);
CREATE INDEX IDX_AUDIT_LOG_DATA ON AUDIT_LOG (DATA);
