CREATE TABLE TENANT (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    API_KEY VARCHAR(100) NOT NULL,
    STATUS CHAR(1) DEFAULT 'A' NOT NULL
);
ALTER TABLE TENANT ADD CONSTRAINT PK_TENANT PRIMARY KEY (ID);
CREATE UNIQUE INDEX UQ_TENANT_API_KEY ON TENANT (API_KEY);

CREATE TABLE SYNC_LOG (
    ID BIGINT NOT NULL,
    EMPRESA_ID INTEGER NOT NULL,
    TABELA VARCHAR(50) NOT NULL,
    CHAVE VARCHAR(100) NOT NULL,
    OPERACAO CHAR(1) NOT NULL,
    DATA TIMESTAMP NOT NULL,
    HASH_UNICO VARCHAR(64)
);
ALTER TABLE SYNC_LOG ADD CONSTRAINT PK_SYNC_LOG PRIMARY KEY (ID);
CREATE INDEX IDX_SYNC_LOG_DATA_ID ON SYNC_LOG (DATA, ID);

CREATE TABLE SYNC_STAGING (
    ID BIGINT NOT NULL,
    EMPRESA_ID INTEGER NOT NULL,
    TABELA VARCHAR(50) NOT NULL,
    CHAVE VARCHAR(100),
    OPERACAO CHAR(1) NOT NULL,
    PAYLOAD BLOB SUB_TYPE TEXT NOT NULL,
    DATA_RECEBIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PROCESSADO CHAR(1) DEFAULT 'N' NOT NULL,
    TENTATIVAS INTEGER DEFAULT 0 NOT NULL,
    STATUS CHAR(1) DEFAULT 'N' NOT NULL
);
ALTER TABLE SYNC_STAGING ADD CONSTRAINT PK_SYNC_STAGING PRIMARY KEY (ID);
CREATE GENERATOR GEN_SYNC_STAGING_ID;
SET TERM !! ;
CREATE TRIGGER BI_SYNC_STAGING FOR SYNC_STAGING
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_SYNC_STAGING_ID, 1);
END!!
SET TERM ; !!
CREATE INDEX IDX_SYNC_STAGING_STATUS ON SYNC_STAGING (STATUS);
CREATE INDEX IDX_SYNC_STAGING_EMPRESA ON SYNC_STAGING (EMPRESA_ID, STATUS, ID);

CREATE TABLE ASSINATURA (
    ID INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    STATUS CHAR(1) DEFAULT 'A' NOT NULL,
    DATA_VENCIMENTO DATE
);
ALTER TABLE ASSINATURA ADD CONSTRAINT PK_ASSINATURA PRIMARY KEY (ID);

CREATE TABLE AUDIT_LOG (
    ID BIGINT NOT NULL,
    USUARIO_ID INTEGER,
    ACAO VARCHAR(50) NOT NULL,
    TABELA VARCHAR(50),
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE AUDIT_LOG ADD CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ID);
CREATE INDEX IDX_AUDIT_LOG_DATA ON AUDIT_LOG (DATA);
