-- Technical audit/evidence foundation.
CREATE TABLE LEGAL_EVENT_LOG (
    ID BIGINT NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    USUARIO_ID INTEGER,
    DEVICE_ID VARCHAR(100),
    EVENT_ID VARCHAR(100) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    ACAO VARCHAR(50) NOT NULL,
    RECURSO VARCHAR(100),
    RECURSO_CHAVE VARCHAR(150),
    SERVER_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLIENT_TIMESTAMP TIMESTAMP,
    CORRELATION_ID VARCHAR(100),
    PREVIOUS_HASH VARCHAR(64),
    EVENT_HASH VARCHAR(64) NOT NULL,
    RESULTADO VARCHAR(30) NOT NULL,
    METADATA BLOB SUB_TYPE TEXT,
    PAYLOAD_HASH VARCHAR(64)
);
ALTER TABLE LEGAL_EVENT_LOG ADD CONSTRAINT PK_LEGAL_EVENT_LOG PRIMARY KEY (ID);
CREATE GENERATOR GEN_LEGAL_EVENT_LOG_ID;
SET TERM !! ;
CREATE TRIGGER BI_LEGAL_EVENT_LOG FOR LEGAL_EVENT_LOG ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_LEGAL_EVENT_LOG_ID, 1);
END!!
SET TERM ; !!
CREATE UNIQUE INDEX UQ_LEGAL_EVENT_EVENT_ID ON LEGAL_EVENT_LOG (TENANT_ID, EVENT_ID);
CREATE INDEX IDX_LEGAL_EVENT_TIME ON LEGAL_EVENT_LOG (TENANT_ID, SERVER_TIMESTAMP, ID);
CREATE INDEX IDX_LEGAL_EVENT_DEVICE ON LEGAL_EVENT_LOG (TENANT_ID, DEVICE_ID, SERVER_TIMESTAMP);
CREATE INDEX IDX_LEGAL_EVENT_CORRELATION ON LEGAL_EVENT_LOG (CORRELATION_ID);
CREATE INDEX IDX_LEGAL_EVENT_HASH ON LEGAL_EVENT_LOG (EVENT_HASH);

CREATE TABLE INTEGRATION_DEVICE (
    ID BIGINT NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    DEVICE_ID VARCHAR(100) NOT NULL,
    DEVICE_TYPE VARCHAR(30) NOT NULL,
    NAME VARCHAR(100),
    STATUS CHAR(1) DEFAULT 'A' NOT NULL,
    PROTOCOL_VERSION INTEGER DEFAULT 1 NOT NULL,
    LAST_SEEN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE INTEGRATION_DEVICE ADD CONSTRAINT PK_INTEGRATION_DEVICE PRIMARY KEY (ID);
CREATE GENERATOR GEN_INTEGRATION_DEVICE_ID;
SET TERM !! ;
CREATE TRIGGER BI_INTEGRATION_DEVICE FOR INTEGRATION_DEVICE ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_INTEGRATION_DEVICE_ID, 1);
END!!
SET TERM ; !!
CREATE UNIQUE INDEX UQ_DEVICE_TENANT_ID ON INTEGRATION_DEVICE (TENANT_ID, DEVICE_ID);
CREATE INDEX IDX_DEVICE_STATUS ON INTEGRATION_DEVICE (TENANT_ID, STATUS);
