CREATE TABLE SYNC_LOCK (
    ID INTEGER NOT NULL,
    PROCESSO VARCHAR(50),
    DATA_INICIO TIMESTAMP,
    ATIVO CHAR(1) DEFAULT 'S'
);

ALTER TABLE SYNC_LOCK ADD CONSTRAINT PK_SYNC_LOCK PRIMARY KEY (ID);

INSERT INTO SYNC_LOCK (ID, PROCESSO, DATA_INICIO, ATIVO)
VALUES (1, 'SYNC_PROCESSOR', CURRENT_TIMESTAMP, 'N');
