ALTER TABLE SYNC_STAGING ADD TENTATIVAS INTEGER DEFAULT 0;
ALTER TABLE SYNC_STAGING ADD STATUS CHAR(1) DEFAULT 'N'; -- N=novo, P=processando, S=sucesso, E=erro

CREATE INDEX IDX_SYNC_STAGING_STATUS ON SYNC_STAGING (STATUS);
