-- Canonical SYNC_STAGING schema is maintained in database/full.sql.
-- This compatibility migration upgrades an existing database that was created
-- from the older staging.sql definition.

ALTER TABLE SYNC_STAGING ADD EMPRESA_ID INTEGER;
ALTER TABLE SYNC_STAGING ADD TENTATIVAS INTEGER DEFAULT 0;
ALTER TABLE SYNC_STAGING ADD STATUS CHAR(1) DEFAULT 'N';

UPDATE SYNC_STAGING
SET EMPRESA_ID = COALESCE(EMPRESA_ID, 1),
    TENTATIVAS = COALESCE(TENTATIVAS, 0),
    STATUS = CASE
      WHEN COALESCE(PROCESSADO, 'N') = 'S' THEN 'S'
      ELSE 'N'
    END;

ALTER TABLE SYNC_STAGING ALTER EMPRESA_ID SET NOT NULL;
ALTER TABLE SYNC_STAGING ALTER TENTATIVAS SET NOT NULL;
ALTER TABLE SYNC_STAGING ALTER STATUS SET NOT NULL;

CREATE INDEX IDX_SYNC_STAGING_STATUS ON SYNC_STAGING (STATUS);
CREATE INDEX IDX_SYNC_STAGING_EMPRESA ON SYNC_STAGING (EMPRESA_ID, STATUS, ID);
