-- This compatibility migration upgrades an existing database that was created
-- from the older staging.sql definition.
-- Canonical SYNC_STAGING schema is maintained in database/full.sql.

ALTER TABLE SYNC_STAGING ADD EMPRESA_ID INTEGER;
ALTER TABLE SYNC_STAGING ADD TENTATIVAS INTEGER DEFAULT 0;
ALTER TABLE SYNC_STAGING ADD STATUS CHAR(1) DEFAULT 'N';
ALTER TABLE SYNC_STAGING ADD HASH_UNICO VARCHAR(64);
ALTER TABLE SYNC_STAGING ADD DATA_PROCESSAMENTO TIMESTAMP;
ALTER TABLE SYNC_STAGING ADD WORKER_ID VARCHAR(100);

UPDATE SYNC_STAGING
SET EMPRESA_ID = COALESCE(EMPRESA_ID, 1),
    TENTATIVAS = COALESCE(TENTATIVAS, 0),
    STATUS = CASE
      WHEN COALESCE(PROCESSADO, 'N') = 'S' THEN 'S'
      ELSE 'N'
    END;

ALTER TABLE SYNC_STAGING ALTER EMPRESA_ID SET NOT NULL;
ALTER TABLE SYNC_STAGING ALTER TENTATIVAS SET NOT NULL;
ALTER TABLE SYNC_STAGING ALTER STATUS SET NOT NULL;

CREATE INDEX IDX_SYNC_STAGING_STATUS ON SYNC_STAGING (STATUS);
CREATE INDEX IDX_SYNC_STAGING_EMPRESA ON SYNC_STAGING (EMPRESA_ID, STATUS, ID);
CREATE INDEX IDX_SYNC_STAGING_RECOVERY ON SYNC_STAGING (STATUS, DATA_PROCESSAMENTO);
CREATE UNIQUE INDEX UQ_SYNC_STAGING_HASH ON SYNC_STAGING (EMPRESA_ID, HASH_UNICO);
