CREATE TABLE SYNC_STAGING (
    ID BIGINT NOT NULL,
    TABELA VARCHAR(50),
    CHAVE VARCHAR(100),
    OPERACAO CHAR(1),
    PAYLOAD BLOB SUB_TYPE TEXT,
    DATA_RECEBIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROCESSADO CHAR(1) DEFAULT 'N'
);

ALTER TABLE SYNC_STAGING ADD CONSTRAINT PK_SYNC_STAGING PRIMARY KEY (ID);

CREATE GENERATOR GEN_SYNC_STAGING_ID;

SET TERM !! ;
CREATE TRIGGER BI_SYNC_STAGING FOR SYNC_STAGING
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SYNC_STAGING_ID, 1);
END!!
SET TERM ; !!