-- Versioned additive migration for existing Firebird installations.
-- Safe for databases that already contain these fields: each block checks
-- RDB$RELATION_FIELDS before issuing ALTER TABLE.

SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='INTEGRATION_DEVICE' AND RDB$FIELD_NAME='CREDENTIAL_HASH')) THEN
    EXECUTE STATEMENT 'ALTER TABLE INTEGRATION_DEVICE ADD CREDENTIAL_HASH VARCHAR(64)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='INTEGRATION_DEVICE' AND RDB$FIELD_NAME='CREDENTIAL_CREATED_AT')) THEN
    EXECUTE STATEMENT 'ALTER TABLE INTEGRATION_DEVICE ADD CREDENTIAL_CREATED_AT TIMESTAMP';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='INTEGRATION_DEVICE' AND RDB$FIELD_NAME='CREDENTIAL_EXPIRES_AT')) THEN
    EXECUTE STATEMENT 'ALTER TABLE INTEGRATION_DEVICE ADD CREDENTIAL_EXPIRES_AT TIMESTAMP';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='INTEGRATION_DEVICE' AND RDB$FIELD_NAME='CREDENTIAL_VERSION')) THEN
    EXECUTE STATEMENT 'ALTER TABLE INTEGRATION_DEVICE ADD CREDENTIAL_VERSION INTEGER DEFAULT 1 NOT NULL';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='INTEGRATION_DEVICE' AND RDB$FIELD_NAME='SCOPES')) THEN
    EXECUTE STATEMENT 'ALTER TABLE INTEGRATION_DEVICE ADD SCOPES VARCHAR(500)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='INTEGRATION_DEVICE' AND RDB$FIELD_NAME='LAST_LATITUDE')) THEN
    EXECUTE STATEMENT 'ALTER TABLE INTEGRATION_DEVICE ADD LAST_LATITUDE DECIMAL(9,6)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='INTEGRATION_DEVICE' AND RDB$FIELD_NAME='LAST_LONGITUDE')) THEN
    EXECUTE STATEMENT 'ALTER TABLE INTEGRATION_DEVICE ADD LAST_LONGITUDE DECIMAL(9,6)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='INTEGRATION_DEVICE' AND RDB$FIELD_NAME='LOCATION_UPDATED_AT')) THEN
    EXECUTE STATEMENT 'ALTER TABLE INTEGRATION_DEVICE ADD LOCATION_UPDATED_AT TIMESTAMP';
END^

SET TERM ; ^

-- Existing installations may already have the credential index under the
-- legacy migration. The index is intentionally not recreated here.
