-- Fine-tuning artifact lineage registry: immutable training artifacts.
SET TERM ^ ;

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_FINE_TUNE_ARTIFACT')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_FINE_TUNE_ARTIFACT (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL,
      ARTIFACT_HASH VARCHAR(64) NOT NULL, DATASET_HASH VARCHAR(64) NOT NULL,
      DATASET_VERSION INTEGER DEFAULT 1 NOT NULL, EXAMPLES_COUNT INTEGER DEFAULT 0 NOT NULL,
      TRAIN_COUNT INTEGER DEFAULT 0 NOT NULL, VALIDATION_COUNT INTEGER DEFAULT 0 NOT NULL,
      VALIDATION_RATIO DECIMAL(9,6), PROMPT_VERSION_ID BIGINT, BASELINE_PROMPT_VERSION_ID BIGINT,
      MODEL VARCHAR(150), PROVIDER VARCHAR(80), TRAINING_CONFIG_JSON BLOB SUB_TYPE TEXT,
      LINEAGE_JSON BLOB SUB_TYPE TEXT, STATUS VARCHAR(20) DEFAULT ''READY'' NOT NULL,
      CREATED_BY VARCHAR(150), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_FINE_TUNE_ARTIFACT PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_FINE_TUNE_ARTIFACT_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_FINE_TUNE_ARTIFACT_ID'; END
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_FINE_TUNE_ARTIFACT_HASH')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_FINE_TUNE_ARTIFACT_HASH ON AI_FINE_TUNE_ARTIFACT (TENANT_ID, ARTIFACT_HASH)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_FINE_TUNE_ARTIFACT_DATASET')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_FINE_TUNE_ARTIFACT_DATASET ON AI_FINE_TUNE_ARTIFACT (TENANT_ID, DATASET_HASH, CREATED_AT, ID)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_FINE_TUNE_ARTIFACT_PROMPT')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_FINE_TUNE_ARTIFACT_PROMPT ON AI_FINE_TUNE_ARTIFACT (TENANT_ID, PROMPT_VERSION_ID, CREATED_AT, ID)';
END^

SET TERM ; ^
