-- AI/RAG governance foundation: Firebird dialect.
-- Logical schema is documented in database/migrations/README.md.
SET TERM ^ ;

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_DOCUMENT')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_DOCUMENT (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, SOURCE_TYPE VARCHAR(40) NOT NULL,
      EXTERNAL_KEY VARCHAR(200) NOT NULL, TITLE VARCHAR(250), VERSION_NO INTEGER DEFAULT 1 NOT NULL,
      CHECKSUM_SHA256 VARCHAR(64) NOT NULL, CLASSIFICATION VARCHAR(30) DEFAULT ''INTERNAL'' NOT NULL,
      ACL_JSON BLOB SUB_TYPE TEXT, STATUS VARCHAR(20) DEFAULT ''ACTIVE'' NOT NULL,
      METADATA_JSON BLOB SUB_TYPE TEXT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, DELETED_AT TIMESTAMP,
      CONSTRAINT PK_AI_DOCUMENT PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_DOCUMENT_CHUNK')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_DOCUMENT_CHUNK (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, DOCUMENT_ID BIGINT NOT NULL,
      CHUNK_INDEX INTEGER NOT NULL, CONTENT BLOB SUB_TYPE TEXT NOT NULL, CONTENT_HASH VARCHAR(64) NOT NULL,
      TOKEN_COUNT INTEGER, VECTOR_KEY VARCHAR(200), EMBEDDING_MODEL VARCHAR(150),
      STATUS VARCHAR(20) DEFAULT ''PENDING'' NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_DOCUMENT_CHUNK PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_INGESTION_JOB')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_INGESTION_JOB (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, DOCUMENT_ID BIGINT,
      IDEMPOTENCY_KEY VARCHAR(150) NOT NULL, STATUS VARCHAR(20) DEFAULT ''QUEUED'' NOT NULL,
      STAGE VARCHAR(30) DEFAULT ''RECEIVED'' NOT NULL, ERROR_CODE VARCHAR(80),
      ERROR_MESSAGE VARCHAR(500), CORRELATION_ID VARCHAR(128),
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, STARTED_AT TIMESTAMP, FINISHED_AT TIMESTAMP,
      CONSTRAINT PK_AI_INGESTION_JOB PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_QUERY_AUDIT')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_QUERY_AUDIT (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, CORRELATION_ID VARCHAR(128) NOT NULL,
      MODEL VARCHAR(150), PROVIDER VARCHAR(80), RETRIEVAL_TOP_K INTEGER,
      RETRIEVAL_COUNT INTEGER DEFAULT 0 NOT NULL, PROMPT_VERSION VARCHAR(50),
      RESULT_STATUS VARCHAR(30) NOT NULL, LATENCY_MS BIGINT, INPUT_TOKENS INTEGER,
      OUTPUT_TOKENS INTEGER, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_QUERY_AUDIT PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_EVAL_CASE')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_EVAL_CASE (
      ID BIGINT NOT NULL, TENANT_ID INTEGER, NAME VARCHAR(150) NOT NULL,
      VERSION_NO INTEGER DEFAULT 1 NOT NULL, INPUT_TEXT BLOB SUB_TYPE TEXT NOT NULL,
      EXPECTED_JSON BLOB SUB_TYPE TEXT, ACTIVE CHAR(1) DEFAULT ''S'' NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_EVAL_CASE PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_EVAL_RUN')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_EVAL_RUN (
      ID BIGINT NOT NULL, TENANT_ID INTEGER, EVAL_CASE_ID BIGINT NOT NULL,
      MODEL VARCHAR(150), PROVIDER VARCHAR(80), SCORE DECIMAL(9,4),
      GROUNDEDNESS_SCORE DECIMAL(9,4), LATENCY_MS BIGINT, DETAILS_JSON BLOB SUB_TYPE TEXT,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_EVAL_RUN PRIMARY KEY (ID))';
END^

EXECUTE BLOCK AS BEGIN IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_DOCUMENT_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_DOCUMENT_ID'; END^
EXECUTE BLOCK AS BEGIN IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_DOCUMENT_CHUNK_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_DOCUMENT_CHUNK_ID'; END^
EXECUTE BLOCK AS BEGIN IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_INGESTION_JOB_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_INGESTION_JOB_ID'; END^
EXECUTE BLOCK AS BEGIN IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_QUERY_AUDIT_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_QUERY_AUDIT_ID'; END^
EXECUTE BLOCK AS BEGIN IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_EVAL_CASE_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_EVAL_CASE_ID'; END^
EXECUTE BLOCK AS BEGIN IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_EVAL_RUN_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_EVAL_RUN_ID'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_DOCUMENT_TENANT_KEY')) THEN EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_DOCUMENT_TENANT_KEY ON AI_DOCUMENT (TENANT_ID, EXTERNAL_KEY)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_DOCUMENT_TENANT_STATUS')) THEN EXECUTE STATEMENT 'CREATE INDEX IDX_AI_DOCUMENT_TENANT_STATUS ON AI_DOCUMENT (TENANT_ID, STATUS)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_CHUNK_DOCUMENT')) THEN EXECUTE STATEMENT 'CREATE INDEX IDX_AI_CHUNK_DOCUMENT ON AI_DOCUMENT_CHUNK (TENANT_ID, DOCUMENT_ID, CHUNK_INDEX)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_INGESTION_TENANT_STATUS')) THEN EXECUTE STATEMENT 'CREATE INDEX IDX_AI_INGESTION_TENANT_STATUS ON AI_INGESTION_JOB (TENANT_ID, STATUS, ID)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_INGESTION_IDEMPOTENCY')) THEN EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_INGESTION_IDEMPOTENCY ON AI_INGESTION_JOB (TENANT_ID, IDEMPOTENCY_KEY)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_QUERY_TENANT_TIME')) THEN EXECUTE STATEMENT 'CREATE INDEX IDX_AI_QUERY_TENANT_TIME ON AI_QUERY_AUDIT (TENANT_ID, CREATED_AT, ID)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_EVAL_CASE_ACTIVE')) THEN EXECUTE STATEMENT 'CREATE INDEX IDX_AI_EVAL_CASE_ACTIVE ON AI_EVAL_CASE (TENANT_ID, ACTIVE)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='AI_EVAL_RUN' AND RDB$FIELD_NAME='PROMPT_VERSION_ID')) THEN
    EXECUTE STATEMENT 'ALTER TABLE AI_EVAL_RUN ADD PROMPT_VERSION_ID BIGINT';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='AI_EVAL_RUN' AND RDB$FIELD_NAME='BASELINE_PROMPT_VERSION_ID')) THEN
    EXECUTE STATEMENT 'ALTER TABLE AI_EVAL_RUN ADD BASELINE_PROMPT_VERSION_ID BIGINT';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_EVAL_RUN_TENANT_PROMPT_TIME')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_EVAL_RUN_TENANT_PROMPT_TIME ON AI_EVAL_RUN (TENANT_ID, PROMPT_VERSION_ID, CREATED_AT, ID)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_QUERY_FEEDBACK')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_QUERY_FEEDBACK (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, AUDIT_ID BIGINT NOT NULL,
      FEEDBACK_TYPE VARCHAR(30) NOT NULL, LABEL VARCHAR(30), RATING DECIMAL(9,4),
      COMMENT_TEXT VARCHAR(2000), CREATED_BY VARCHAR(150), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_QUERY_FEEDBACK PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_QUERY_FEEDBACK_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_QUERY_FEEDBACK_ID'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_FEEDBACK_TENANT_AUDIT')) THEN EXECUTE STATEMENT 'CREATE INDEX IDX_AI_FEEDBACK_TENANT_AUDIT ON AI_QUERY_FEEDBACK (TENANT_ID, AUDIT_ID, CREATED_AT)'; END^


EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_REFINEMENT_ITEM')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_REFINEMENT_ITEM (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, AUDIT_ID BIGINT, PROMPT_VERSION_ID BIGINT,
      FEEDBACK_ID BIGINT, TYPE VARCHAR(40) NOT NULL, SOURCE VARCHAR(40) NOT NULL,
      TITLE VARCHAR(250) NOT NULL, PROPOSED_CHANGE_JSON BLOB SUB_TYPE TEXT NOT NULL,
      STATUS VARCHAR(20) DEFAULT ''PENDING'' NOT NULL, CREATED_BY VARCHAR(150),
      REVIEWED_BY VARCHAR(150), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      REVIEWED_AT TIMESTAMP, CONSTRAINT PK_AI_REFINEMENT_ITEM PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_REFINEMENT_ITEM_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_REFINEMENT_ITEM_ID'; END
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_REFINEMENT_TENANT_STATUS')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_REFINEMENT_TENANT_STATUS ON AI_REFINEMENT_ITEM (TENANT_ID, STATUS, CREATED_AT, ID)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_REFINEMENT_TENANT_FEEDBACK')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_REFINEMENT_TENANT_FEEDBACK ON AI_REFINEMENT_ITEM (TENANT_ID, FEEDBACK_ID)';
END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='AI_REFINEMENT_ITEM' AND RDB$FIELD_NAME='ACCEPT_IDEMPOTENCY_KEY')) THEN
    EXECUTE STATEMENT 'ALTER TABLE AI_REFINEMENT_ITEM ADD ACCEPT_IDEMPOTENCY_KEY VARCHAR(150)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_REFINEMENT_ACCEPT_KEY')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_REFINEMENT_ACCEPT_KEY ON AI_REFINEMENT_ITEM (TENANT_ID, ACCEPT_IDEMPOTENCY_KEY)';
END^


EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='AI_QUERY_FEEDBACK' AND RDB$FIELD_NAME='IDEMPOTENCY_KEY')) THEN
    EXECUTE STATEMENT 'ALTER TABLE AI_QUERY_FEEDBACK ADD IDEMPOTENCY_KEY VARCHAR(150)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_FEEDBACK_IDEMPOTENCY')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_FEEDBACK_IDEMPOTENCY ON AI_QUERY_FEEDBACK (TENANT_ID, IDEMPOTENCY_KEY)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='AI_REFINEMENT_ITEM' AND RDB$FIELD_NAME='BASE_PROMPT_VERSION_ID')) THEN
    EXECUTE STATEMENT 'ALTER TABLE AI_REFINEMENT_ITEM ADD BASE_PROMPT_VERSION_ID BIGINT';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_REFINEMENT_TENANT_BASE_PROMPT')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_REFINEMENT_TENANT_BASE_PROMPT ON AI_REFINEMENT_ITEM (TENANT_ID, BASE_PROMPT_VERSION_ID)';
END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_PROMPT_PROMOTION_AUDIT')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_PROMPT_PROMOTION_AUDIT (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, PROMPT_VERSION_ID BIGINT NOT NULL,
      BASELINE_VERSION_ID BIGINT, RELEASE_ID BIGINT, EVAL_RUN_COUNT INTEGER DEFAULT 0 NOT NULL,
      CANDIDATE_SCORE DECIMAL(9,4), BASELINE_SCORE DECIMAL(9,4), DELTA DECIMAL(9,4),
      CANARY_STATUS VARCHAR(20), DECISION VARCHAR(30) NOT NULL, DECIDED_BY VARCHAR(150),
      DECIDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CORRELATION_ID VARCHAR(128),
      REASON VARCHAR(1000), DETAILS_JSON BLOB SUB_TYPE TEXT,
      CONSTRAINT PK_AI_PROMPT_PROMOTION_AUDIT PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_PROMPT_PROMOTION_AUDIT_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_PROMPT_PROMOTION_AUDIT_ID'; END^
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_PROMOTION_AUDIT_TENANT_PROMPT')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_PROMOTION_AUDIT_TENANT_PROMPT ON AI_PROMPT_PROMOTION_AUDIT (TENANT_ID, PROMPT_VERSION_ID, DECIDED_AT, ID)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_PROMOTION_AUDIT_TENANT_TIME')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_PROMOTION_AUDIT_TENANT_TIME ON AI_PROMPT_PROMOTION_AUDIT (TENANT_ID, DECIDED_AT, ID)';
END^

SET TERM ; ^
