SET TERM ^ ;
EXECUTE BLOCK AS BEGIN
 IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_AGENT_EXECUTION')) THEN
 EXECUTE STATEMENT 'CREATE TABLE AI_AGENT_EXECUTION (
 ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, EXECUTION_HASH VARCHAR(64) NOT NULL,
 AGENT_NAME VARCHAR(120) NOT NULL, SKILL_NAME VARCHAR(120), PLAN_ID VARCHAR(150),
 STATUS VARCHAR(30) DEFAULT ''RUNNING'' NOT NULL, STEP_COUNT INTEGER DEFAULT 0 NOT NULL,
 MAX_STEPS INTEGER DEFAULT 3 NOT NULL, TIMEOUT_BUDGET_MS BIGINT DEFAULT 15000 NOT NULL,
 APPROVAL_REQUIRED INTEGER DEFAULT 0 NOT NULL, APPROVAL_ID VARCHAR(150),
 CORRELATION_ID VARCHAR(150) NOT NULL, IDEMPOTENCY_KEY VARCHAR(150),
 CREATED_BY VARCHAR(150), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 FINISHED_AT TIMESTAMP, CONSTRAINT PK_AI_AGENT_EXECUTION PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_AGENT_EXECUTION_ID')) THEN
 EXECUTE STATEMENT 'CREATE SEQUENCE GEN_AI_AGENT_EXECUTION_ID';
END^
EXECUTE BLOCK AS BEGIN
 IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_AGENT_EXEC_TENANT_HASH')) THEN
 EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_AGENT_EXEC_TENANT_HASH ON AI_AGENT_EXECUTION (TENANT_ID, EXECUTION_HASH)';
END^
SET TERM ; ^