-- Fine-tuned / governed model version registry.
SET TERM ^ ;
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_MODEL_VERSION')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_MODEL_VERSION (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, MODEL_HASH VARCHAR(64) NOT NULL,
      RUN_ID BIGINT, ARTIFACT_ID BIGINT, PROVIDER VARCHAR(80) NOT NULL, MODEL_NAME VARCHAR(150) NOT NULL,
      MODEL_VERSION VARCHAR(150), MODEL_URI VARCHAR(500), STATUS VARCHAR(20) DEFAULT ''REGISTERED'' NOT NULL,
      METADATA_JSON BLOB SUB_TYPE TEXT, CREATED_BY VARCHAR(150), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_MODEL_VERSION PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_MODEL_VERSION_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_MODEL_VERSION_ID'; END
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_MODEL_VERSION_HASH')) THEN EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_MODEL_VERSION_HASH ON AI_MODEL_VERSION (TENANT_ID, MODEL_HASH)'; END
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_MODEL_VERSION_RUN')) THEN EXECUTE STATEMENT 'CREATE INDEX IDX_AI_MODEL_VERSION_RUN ON AI_MODEL_VERSION (TENANT_ID, RUN_ID, CREATED_AT, ID)'; END
END^
SET TERM ; ^
