CREATE TABLE LEGAL_ACCEPTANCE (
  ID BIGINT NOT NULL,
  TENANT_ID INTEGER NOT NULL,
  SUBJECT_ID VARCHAR(150) NOT NULL,
  POLICY_TYPE VARCHAR(40) NOT NULL,
  POLICY_VERSION VARCHAR(80) NOT NULL,
  ACTION VARCHAR(20) NOT NULL,
  ACCEPTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CORRELATION_ID VARCHAR(128),
  SOURCE VARCHAR(40),
  CONSTRAINT PK_LEGAL_ACCEPTANCE PRIMARY KEY (ID)
);
CREATE SEQUENCE GEN_LEGAL_ACCEPTANCE_ID;
CREATE INDEX IDX_LEGAL_ACCEPTANCE_TENANT_SUBJECT ON LEGAL_ACCEPTANCE (TENANT_ID,SUBJECT_ID,ACCEPTED_AT);
CREATE INDEX IDX_LEGAL_ACCEPTANCE_TENANT_POLICY ON LEGAL_ACCEPTANCE (TENANT_ID,POLICY_TYPE,POLICY_VERSION,ACCEPTED_AT);
