-- AI Sales Acceleration foundation: Firebird dialect.
SET TERM ^ ;

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_SALES_LEAD_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_SALES_LEAD_ID'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_SALES_OPPORTUNITY_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_SALES_OPPORTUNITY_ID'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_SALES_ACTIVITY_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_SALES_ACTIVITY_ID'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_SALES_NEXT_ACTION_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_SALES_NEXT_ACTION_ID'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='SALES_LEAD')) THEN
    EXECUTE STATEMENT 'CREATE TABLE SALES_LEAD (
      ID BIGINT NOT NULL,
      TENANT_ID INTEGER NOT NULL,
      EXTERNAL_KEY VARCHAR(200) NOT NULL,
      NAME VARCHAR(200) NOT NULL,
      EMAIL VARCHAR(250),
      COMPANY VARCHAR(250),
      SOURCE VARCHAR(80),
      STATUS VARCHAR(30) DEFAULT ''NEW'' NOT NULL,
      FIT_SCORE DECIMAL(5,4),
      INTENT_SCORE DECIMAL(5,4),
      PRIORITY_SCORE DECIMAL(5,4),
      LAST_CONTACT_AT TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      METADATA BLOB SUB_TYPE TEXT,
      CONSTRAINT PK_SALES_LEAD PRIMARY KEY (ID),
      CONSTRAINT UQ_SALES_LEAD_TENANT_KEY UNIQUE (TENANT_ID, EXTERNAL_KEY)
    )'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='SALES_OPPORTUNITY')) THEN
    EXECUTE STATEMENT 'CREATE TABLE SALES_OPPORTUNITY (
      ID BIGINT NOT NULL,
      TENANT_ID INTEGER NOT NULL,
      LEAD_ID BIGINT NOT NULL,
      TITLE VARCHAR(250) NOT NULL,
      STAGE VARCHAR(40) DEFAULT ''QUALIFICATION'' NOT NULL,
      STATUS VARCHAR(30) DEFAULT ''OPEN'' NOT NULL,
      AMOUNT DECIMAL(18,2),
      PROBABILITY DECIMAL(5,4),
      EXPECTED_CLOSE_AT TIMESTAMP,
      OWNER_ID INTEGER,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      METADATA BLOB SUB_TYPE TEXT,
      CONSTRAINT PK_SALES_OPPORTUNITY PRIMARY KEY (ID),
      CONSTRAINT FK_SALES_OPP_LEAD FOREIGN KEY (LEAD_ID) REFERENCES SALES_LEAD(ID)
    )'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='SALES_ACTIVITY')) THEN
    EXECUTE STATEMENT 'CREATE TABLE SALES_ACTIVITY (
      ID BIGINT NOT NULL,
      TENANT_ID INTEGER NOT NULL,
      OPPORTUNITY_ID BIGINT,
      LEAD_ID BIGINT,
      IDEMPOTENCY_KEY VARCHAR(200) NOT NULL,
      ACTIVITY_TYPE VARCHAR(40) NOT NULL,
      CHANNEL VARCHAR(40),
      SUBJECT VARCHAR(250),
      OUTCOME VARCHAR(80),
      OCCURRED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      PAYLOAD BLOB SUB_TYPE TEXT,
      CONSTRAINT PK_SALES_ACTIVITY PRIMARY KEY (ID),
      CONSTRAINT UQ_SALES_ACTIVITY_TENANT_KEY UNIQUE (TENANT_ID, IDEMPOTENCY_KEY)
    )'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='SALES_NEXT_ACTION')) THEN
    EXECUTE STATEMENT 'CREATE TABLE SALES_NEXT_ACTION (
      ID BIGINT NOT NULL,
      TENANT_ID INTEGER NOT NULL,
      OPPORTUNITY_ID BIGINT NOT NULL,
      ACTION_TYPE VARCHAR(50) NOT NULL,
      DUE_AT TIMESTAMP,
      STATUS VARCHAR(30) DEFAULT ''PROPOSED'' NOT NULL,
      RATIONALE BLOB SUB_TYPE TEXT,
      CONFIDENCE DECIMAL(5,4),
      SOURCE VARCHAR(30) DEFAULT ''AI'' NOT NULL,
      REQUIRES_APPROVAL CHAR(1) DEFAULT ''Y'' NOT NULL,
      APPROVED_BY INTEGER,
      APPROVED_AT TIMESTAMP,
      COMPLETED_AT TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_SALES_NEXT_ACTION PRIMARY KEY (ID)
    )'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_SALES_LEAD_TENANT_STATUS')) THEN EXECUTE STATEMENT 'CREATE INDEX IX_SALES_LEAD_TENANT_STATUS ON SALES_LEAD(TENANT_ID, STATUS)'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_SALES_LEAD_TENANT_PRIORITY')) THEN EXECUTE STATEMENT 'CREATE INDEX IX_SALES_LEAD_TENANT_PRIORITY ON SALES_LEAD(TENANT_ID, PRIORITY_SCORE)'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_SALES_OPP_TENANT_STATUS')) THEN EXECUTE STATEMENT 'CREATE INDEX IX_SALES_OPP_TENANT_STATUS ON SALES_OPPORTUNITY(TENANT_ID, STATUS)'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_SALES_OPP_TENANT_LEAD')) THEN EXECUTE STATEMENT 'CREATE INDEX IX_SALES_OPP_TENANT_LEAD ON SALES_OPPORTUNITY(TENANT_ID, LEAD_ID)'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_SALES_ACTIVITY_TENANT_OPP')) THEN EXECUTE STATEMENT 'CREATE INDEX IX_SALES_ACTIVITY_TENANT_OPP ON SALES_ACTIVITY(TENANT_ID, OPPORTUNITY_ID)'; END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_SALES_ACTION_TENANT_OPP')) THEN EXECUTE STATEMENT 'CREATE INDEX IX_SALES_ACTION_TENANT_OPP ON SALES_NEXT_ACTION(TENANT_ID, OPPORTUNITY_ID)'; END^

SET TERM ; ^
