SET TERM ^ ;
EXECUTE BLOCK AS BEGIN
 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_ANALYTICS_RECOMMENDATION_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_ANALYTICS_RECOMMENDATION_ID'; END^
EXECUTE BLOCK AS BEGIN
 IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='ANALYTICS_RECOMMENDATION')) THEN
 EXECUTE STATEMENT 'CREATE TABLE ANALYTICS_RECOMMENDATION (
 ID BIGINT NOT NULL,
 TENANT_ID INTEGER NOT NULL,
 INSIGHT_ID BIGINT NOT NULL,
 TYPE VARCHAR(40) NOT NULL,
 ACTION VARCHAR(80) NOT NULL,
 SEVERITY VARCHAR(20) NOT NULL,
 STATUS VARCHAR(20) DEFAULT ''PROPOSED'' NOT NULL,
 RATIONALE BLOB SUB_TYPE TEXT,
 EVIDENCE_COVERAGE DECIMAL(5,4),
 REQUIRES_APPROVAL CHAR(1) DEFAULT ''Y'' NOT NULL,
 APPROVED_BY INTEGER,
 APPROVED_AT TIMESTAMP,
 CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 CONSTRAINT PK_ANALYTICS_RECOMMENDATION PRIMARY KEY (ID),
 CONSTRAINT UQ_ANALYTICS_REC_TENANT_ID UNIQUE (TENANT_ID,ID),
 CONSTRAINT UQ_ANALYTICS_REC_TENANT_INSIGHT UNIQUE (TENANT_ID,INSIGHT_ID),
 CONSTRAINT FK_ANALYTICS_REC_INSIGHT FOREIGN KEY (TENANT_ID,INSIGHT_ID) REFERENCES ANALYTICS_INSIGHT(TENANT_ID,ID)
 )'; END^
EXECUTE BLOCK AS BEGIN
 IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_ANALYTICS_REC_TENANT_STATUS')) THEN EXECUTE STATEMENT 'CREATE INDEX IX_ANALYTICS_REC_TENANT_STATUS ON ANALYTICS_RECOMMENDATION(TENANT_ID,STATUS)'; END^
SET TERM ; ^
