-- MCP tool-call audit: persistent governance trail for tool execution.
SET TERM ^ ;

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_MCP_TOOL_AUDIT')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_MCP_TOOL_AUDIT (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, CORRELATION_ID VARCHAR(150) NOT NULL,
      TOOL_NAME VARCHAR(120) NOT NULL, CONTRACT_VERSION VARCHAR(30),
      SIDE_EFFECT VARCHAR(30), STATUS VARCHAR(30) NOT NULL,
      INPUT_HASH VARCHAR(64), OUTPUT_HASH VARCHAR(64), ERROR_CODE VARCHAR(100),
      LATENCY_MS BIGINT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_MCP_TOOL_AUDIT PRIMARY KEY (ID))';
END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_MCP_TOOL_AUDIT_ID')) THEN
    EXECUTE STATEMENT 'CREATE SEQUENCE GEN_AI_MCP_TOOL_AUDIT_ID';
END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_MCP_TOOL_AUDIT_TENANT_CORR')) THEN
    EXECUTE STATEMENT 'CREATE INDEX UX_AI_MCP_TOOL_AUDIT_TENANT_CORR ON AI_MCP_TOOL_AUDIT (TENANT_ID, CORRELATION_ID, CREATED_AT, ID)';
END^

SET TERM ; ^