-- Analytics V1 foundation: Firebird dialect.
SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (
    SELECT 1
    FROM RDB$GENERATORS
    WHERE RDB$GENERATOR_NAME='GEN_ANALYTICS_MAPPING_ID'
  )) THEN
    EXECUTE STATEMENT 'CREATE GENERATOR GEN_ANALYTICS_MAPPING_ID';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (
    SELECT 1
    FROM RDB$RELATIONS
    WHERE RDB$RELATION_NAME='ANALYTICS_MAPPING'
  )) THEN
    EXECUTE STATEMENT 'CREATE TABLE ANALYTICS_MAPPING (
      ID BIGINT NOT NULL,
      TENANT_ID INTEGER NOT NULL,
      ENTITY_NAME VARCHAR(80) NOT NULL,
      FIELD_NAME VARCHAR(80) NOT NULL,
      SOURCE_TYPE VARCHAR(20) DEFAULT ''TABLE'' NOT NULL,
      SOURCE_NAME VARCHAR(128) NOT NULL,
      SOURCE_FIELD VARCHAR(128) NOT NULL,
      DATA_TYPE VARCHAR(30) DEFAULT ''TEXT'' NOT NULL,
      STATUS VARCHAR(20) DEFAULT ''ACTIVE'' NOT NULL,
      METADATA BLOB SUB_TYPE TEXT,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_ANALYTICS_MAPPING PRIMARY KEY (ID),
      CONSTRAINT UQ_ANALYTICS_MAPPING_TENANT_ID UNIQUE (TENANT_ID, ID),
      CONSTRAINT UQ_ANALYTICS_MAPPING_TENANT_FIELD UNIQUE (TENANT_ID, ENTITY_NAME, FIELD_NAME),
      CONSTRAINT FK_ANALYTICS_MAPPING_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANT(ID)
    )';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (
    SELECT 1
    FROM RDB$INDICES
    WHERE RDB$INDEX_NAME='IX_ANALYTICS_MAPPING_TENANT_ENTITY'
  )) THEN
    EXECUTE STATEMENT 'CREATE INDEX IX_ANALYTICS_MAPPING_TENANT_ENTITY ON ANALYTICS_MAPPING(TENANT_ID, ENTITY_NAME)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (
    SELECT 1
    FROM RDB$INDICES
    WHERE RDB$INDEX_NAME='IX_ANALYTICS_MAPPING_TENANT_STATUS'
  )) THEN
    EXECUTE STATEMENT 'CREATE INDEX IX_ANALYTICS_MAPPING_TENANT_STATUS ON ANALYTICS_MAPPING(TENANT_ID, STATUS)';
END^

SET TERM ; ^

-- Business Analytics Insight V1: Firebird dialect.
SET TERM ^ ;

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_ANALYTICS_INSIGHT_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_ANALYTICS_INSIGHT_ID'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='ANALYTICS_INSIGHT')) THEN
    EXECUTE STATEMENT 'CREATE TABLE ANALYTICS_INSIGHT (
      ID BIGINT NOT NULL,
      TENANT_ID INTEGER NOT NULL,
      TYPE VARCHAR(40) NOT NULL,
      METRIC VARCHAR(80) NOT NULL,
      PERIOD_START TIMESTAMP NOT NULL,
      PERIOD_END TIMESTAMP NOT NULL,
      CURRENT_VALUE DECIMAL(18,4) NOT NULL,
      PREVIOUS_VALUE DECIMAL(18,4) NOT NULL,
      VARIATION DECIMAL(18,8),
      BASELINE_VALUE DECIMAL(18,4),
      TITLE VARCHAR(250) NOT NULL,
      EXPLANATION BLOB SUB_TYPE TEXT,
      METHODOLOGY BLOB SUB_TYPE TEXT,
      STATUS VARCHAR(20) DEFAULT ''GENERATED'' NOT NULL,
      EVIDENCE_COVERAGE DECIMAL(5,4),
      METADATA BLOB SUB_TYPE TEXT,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_ANALYTICS_INSIGHT PRIMARY KEY (ID),
      CONSTRAINT UQ_ANALYTICS_INSIGHT_TENANT_ID UNIQUE (TENANT_ID, ID),
      CONSTRAINT UQ_ANALYTICS_INSIGHT_PERIOD UNIQUE (TENANT_ID, METRIC, TYPE, PERIOD_START, PERIOD_END)
    )'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_ANALYTICS_INSIGHT_TENANT_METRIC')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IX_ANALYTICS_INSIGHT_TENANT_METRIC ON ANALYTICS_INSIGHT(TENANT_ID, METRIC, CREATED_AT)'; END^

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IX_ANALYTICS_INSIGHT_TENANT_STATUS')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IX_ANALYTICS_INSIGHT_TENANT_STATUS ON ANALYTICS_INSIGHT(TENANT_ID, STATUS, CREATED_AT)'; END^

SET TERM ; ^
