-- Fine-tuning execution registry: immutable run lineage and lifecycle state.
SET TERM ^ ;

EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='AI_FINE_TUNE_RUN')) THEN
    EXECUTE STATEMENT 'CREATE TABLE AI_FINE_TUNE_RUN (
      ID BIGINT NOT NULL, TENANT_ID INTEGER NOT NULL, ARTIFACT_ID BIGINT NOT NULL,
      RUN_HASH VARCHAR(64) NOT NULL, IDEMPOTENCY_KEY VARCHAR(150) NOT NULL,
      EXTERNAL_JOB_ID VARCHAR(200), PROVIDER VARCHAR(80), MODEL VARCHAR(150),
      STATUS VARCHAR(20) DEFAULT ''QUEUED'' NOT NULL,
      TRAINING_CONFIG_JSON BLOB SUB_TYPE TEXT, METRICS_JSON BLOB SUB_TYPE TEXT,
      OUTPUT_MODEL VARCHAR(200), OUTPUT_MODEL_HASH VARCHAR(64),
      ERROR_CODE VARCHAR(100), ERROR_MESSAGE VARCHAR(1000),
      CORRELATION_ID VARCHAR(150), CREATED_BY VARCHAR(150),
      STARTED_AT TIMESTAMP, FINISHED_AT TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_AI_FINE_TUNE_RUN PRIMARY KEY (ID))';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='GEN_AI_FINE_TUNE_RUN_ID')) THEN EXECUTE STATEMENT 'CREATE GENERATOR GEN_AI_FINE_TUNE_RUN_ID'; END
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_FINE_TUNE_RUN_HASH')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_FINE_TUNE_RUN_HASH ON AI_FINE_TUNE_RUN (TENANT_ID, RUN_HASH)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='UX_AI_FINE_TUNE_RUN_IDEMP')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_AI_FINE_TUNE_RUN_IDEMP ON AI_FINE_TUNE_RUN (TENANT_ID, IDEMPOTENCY_KEY)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_FINE_TUNE_RUN_ARTIFACT')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_FINE_TUNE_RUN_ARTIFACT ON AI_FINE_TUNE_RUN (TENANT_ID, ARTIFACT_ID, CREATED_AT, ID)';
END^
EXECUTE BLOCK AS BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME='IDX_AI_FINE_TUNE_RUN_STATUS')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_AI_FINE_TUNE_RUN_STATUS ON AI_FINE_TUNE_RUN (TENANT_ID, STATUS, CREATED_AT, ID)';
END^

SET TERM ; ^
